### ISSUE TITLE
GetEntryAssembly returns null

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/PlatformAbstractions#2]
DefaultApplicationEnvironment assumes GetEntryAssembly() is not null. This is not always the case. e.g. when running tests using TestDriven.net.

```
	at System.Attribute.GetCustomAttributes(Assembly element, Type attributeType, Boolean inherit)
	at System.Attribute.GetCustomAttribute(Assembly element, Type attributeType, Boolean inherit)
	at System.Reflection.CustomAttributeExtensions.GetCustomAttribute[T](Assembly element)
	at Microsoft.Extensions.PlatformAbstractions.DefaultApplicationEnvironment.get_RuntimeFramework()
```

**Comment by davidfowl** [comment]
@natemcmaster This shouldn't repro anymore
